/* Automatically generated by po2tbl.sed from iwc.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"iWarp Client 0.0.1", 2},
  {"Server IP ", 3},
  {"    Port ", 4},
  {"Connect", 5},
  {"Function Generator", 6},
  {"A/O", 7},
  {"D/O", 8},
  {"SEND", 9},
  {"sine", 10},
  {"tangent", 11},
  {"arc sine", 12},
  {"random", 13},
  {"inc", 14},
  {"scan", 15},
  {"Manual Command", 16},
  {"Send command", 17},
  {"Response", 18},
  {"Attempted counter", 19},
  {"DAQ Analog In", 20},
  {"READ", 21},
  {"D/I ", 22},
  {"D/O ", 23},
  {"DO 4", 24},
  {"DO 3", 25},
  {"DO 2", 26},
  {"DO 1", 27},
  {"INV", 28},
  {"Align", 29},
  {"Time Beat Interval ", 30},
  {" x 10ms = ", 31},
  {"ms        ", 32},
  {"  Beat  ", 33},
  {"Couldn't find pixmap file: %s", 34},
  {"Couldn't create pixmap from file: %s", 35},
};

int _msg_tbl_length = 35;
