/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget      *
create_iwc(void)
{
    GtkWidget      *iwc;
    GtkWidget      *vbox1;
    GtkWidget      *frame1;
    GtkWidget      *hbox7;
    GtkWidget      *frame7;
    GtkWidget      *cnt_lemp;
    GtkWidget      *label1;
    GtkWidget      *ip_ent;
    GtkWidget      *label2;
    GtkWidget      *port_ent;
    GtkWidget      *cnt_btn;
    GtkWidget      *hbox2;
    GtkWidget      *fg_frame;
    GtkWidget      *vbox4;
    GtkWidget      *fg_lab;
    GtkWidget      *table1;
    GtkWidget      *label3;
    GtkWidget      *label4;
    GtkWidget      *fg_tbtn;
    GtkWidget      *fg_tbtn2;
    GtkWidget      *fg_com;
    GList          *fg_com_items = NULL;
    GtkWidget      *fg_com_ent;
    GtkWidget      *fg_com2;
    GList          *fg_com2_items = NULL;
    GtkWidget      *fg_com2_ent;
    GtkWidget      *fg_a_ent;
    GtkWidget      *fg_d_ent;
    GtkWidget      *man_frame;
    GtkWidget      *vbox5;
    GtkWidget      *man_lab;
    GtkWidget      *hbox5;
    GtkWidget      *man_ent;
    GtkWidget      *man_btn;
    GtkWidget      *hbox8;
    GtkWidget      *man_ent2;
    GtkWidget      *man_ent3;
    GtkWidget      *frame2;
    GtkWidget      *hbox9;
    GtkWidget      *hs_ent;
    GtkWidget      *hscale1;
    GtkWidget      *draw_frame;
    GtkWidget      *vbox6;
    GtkWidget      *draw_lab;
    GtkWidget      *hbox6;
    GtkWidget      *draw_ent;
    GtkWidget      *hbox11;
    GtkWidget      *draw_ent2;
    GtkWidget      *draw_ent3;
    GtkWidget      *hbox12;
    GtkWidget      *draw_tbtn;
    GtkWidget      *draw;
    GtkWidget      *frame8;
    GtkWidget      *table2;
    GtkWidget      *label5;
    GtkWidget      *label6;
    GtkWidget      *frame12;
    GtkWidget      *di4;
    GtkWidget      *frame11;
    GtkWidget      *di3;
    GtkWidget      *frame10;
    GtkWidget      *di2;
    GtkWidget      *frame9;
    GtkWidget      *di1;
    GtkWidget      *do_ent;
    GtkWidget      *di_ent;
    GtkWidget      *do4;
    GtkWidget      *do3;
    GtkWidget      *do2;
    GtkWidget      *do1;
    GtkWidget      *di_tbtn;
    GtkWidget      *lemp_inv;
    GtkWidget      *do_tbtn;
    GtkWidget      *frame13;
    GtkWidget      *hbox10;
    GtkWidget      *frame14;
    GtkWidget      *beat_lemp;
    GtkWidget      *label7;
    GtkObject      *beat_sb_adj;
    GtkWidget      *beat_sb;
    GtkWidget      *label8;
    GtkWidget      *beat_ent;
    GtkWidget      *label9;
    GtkWidget      *beat_tbtn;
    GtkAccelGroup  *accel_group;
    GtkTooltips    *tooltips;

    tooltips = gtk_tooltips_new();

    accel_group = gtk_accel_group_new();

    iwc = gtk_window_new(GTK_WINDOW_TOPLEVEL);
    gtk_object_set_data(GTK_OBJECT(iwc), "iwc", iwc);
    gtk_window_set_title(GTK_WINDOW(iwc), _("iWarp Client 0.0.1"));

    vbox1 = gtk_vbox_new(FALSE, 0);
    gtk_widget_ref(vbox1);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "vbox1", vbox1,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(vbox1);
    gtk_container_add(GTK_CONTAINER(iwc), vbox1);

    frame1 = gtk_frame_new(NULL);
    gtk_widget_ref(frame1);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "frame1", frame1,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(frame1);
    gtk_box_pack_start(GTK_BOX(vbox1), frame1, TRUE, TRUE, 0);

    hbox7 = gtk_hbox_new(FALSE, 0);
    gtk_widget_ref(hbox7);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "hbox7", hbox7,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(hbox7);
    gtk_container_add(GTK_CONTAINER(frame1), hbox7);

    frame7 = gtk_frame_new(NULL);
    gtk_widget_ref(frame7);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "frame7", frame7,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(frame7);
    gtk_box_pack_start(GTK_BOX(hbox7), frame7, FALSE, FALSE, 0);
    gtk_widget_set_usize(frame7, 32, -2);

    cnt_lemp = create_pixmap(iwc, "lemp0_12.xpm", FALSE);
    gtk_widget_ref(cnt_lemp);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "cnt_lemp", cnt_lemp,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(cnt_lemp);
    gtk_container_add(GTK_CONTAINER(frame7), cnt_lemp);

    label1 = gtk_label_new(_("Server IP "));
    gtk_widget_ref(label1);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "label1", label1,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(label1);
    gtk_box_pack_start(GTK_BOX(hbox7), label1, FALSE, FALSE, 0);

    ip_ent = gtk_entry_new();
    gtk_widget_ref(ip_ent);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "ip_ent", ip_ent,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(ip_ent);
    gtk_box_pack_start(GTK_BOX(hbox7), ip_ent, TRUE, TRUE, 0);
    gtk_widget_set_usize(ip_ent, 100, -2);

    label2 = gtk_label_new(_("    Port "));
    gtk_widget_ref(label2);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "label2", label2,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(label2);
    gtk_box_pack_start(GTK_BOX(hbox7), label2, FALSE, FALSE, 0);

    port_ent = gtk_entry_new();
    gtk_widget_ref(port_ent);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "port_ent", port_ent,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(port_ent);
    gtk_box_pack_start(GTK_BOX(hbox7), port_ent, TRUE, TRUE, 0);
    gtk_widget_set_usize(port_ent, 48, -2);

    cnt_btn = gtk_toggle_button_new_with_label(_("Connect"));
    gtk_widget_ref(cnt_btn);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "cnt_btn", cnt_btn,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(cnt_btn);
    gtk_box_pack_start(GTK_BOX(hbox7), cnt_btn, FALSE, FALSE, 0);

    hbox2 = gtk_hbox_new(FALSE, 0);
    gtk_widget_ref(hbox2);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "hbox2", hbox2,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(hbox2);
    gtk_box_pack_start(GTK_BOX(vbox1), hbox2, TRUE, TRUE, 0);

    fg_frame = gtk_frame_new(NULL);
    gtk_widget_ref(fg_frame);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "fg_frame", fg_frame,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(fg_frame);
    gtk_box_pack_start(GTK_BOX(hbox2), fg_frame, TRUE, TRUE, 0);

    vbox4 = gtk_vbox_new(FALSE, 0);
    gtk_widget_ref(vbox4);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "vbox4", vbox4,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(vbox4);
    gtk_container_add(GTK_CONTAINER(fg_frame), vbox4);

    fg_lab = gtk_label_new(_("Function Generator"));
    gtk_widget_ref(fg_lab);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "fg_lab", fg_lab,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(fg_lab);
    gtk_box_pack_start(GTK_BOX(vbox4), fg_lab, FALSE, FALSE, 0);
    gtk_label_set_justify(GTK_LABEL(fg_lab), GTK_JUSTIFY_LEFT);

    table1 = gtk_table_new(2, 4, FALSE);
    gtk_widget_ref(table1);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "table1", table1,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(table1);
    gtk_box_pack_start(GTK_BOX(vbox4), table1, TRUE, TRUE, 0);

    label3 = gtk_label_new(_("A/O"));
    gtk_widget_ref(label3);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "label3", label3,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(label3);
    gtk_table_attach(GTK_TABLE(table1), label3, 0, 1, 0, 1,
		     (GtkAttachOptions) (0), (GtkAttachOptions) (0), 0, 0);

    label4 = gtk_label_new(_("D/O"));
    gtk_widget_ref(label4);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "label4", label4,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(label4);
    gtk_table_attach(GTK_TABLE(table1), label4, 0, 1, 1, 2,
		     (GtkAttachOptions) (0), (GtkAttachOptions) (0), 0, 0);

    fg_tbtn = gtk_toggle_button_new_with_label(_("SEND"));
    gtk_widget_ref(fg_tbtn);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "fg_tbtn", fg_tbtn,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(fg_tbtn);
    gtk_table_attach(GTK_TABLE(table1), fg_tbtn, 3, 4, 0, 1,
		     (GtkAttachOptions) (0), (GtkAttachOptions) (0), 0, 0);

    fg_tbtn2 = gtk_toggle_button_new_with_label(_("SEND"));
    gtk_widget_ref(fg_tbtn2);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "fg_tbtn2", fg_tbtn2,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(fg_tbtn2);
    gtk_table_attach(GTK_TABLE(table1), fg_tbtn2, 3, 4, 1, 2,
		     (GtkAttachOptions) (0), (GtkAttachOptions) (0), 0, 0);

    fg_com = gtk_combo_new();
    gtk_widget_ref(fg_com);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "fg_com", fg_com,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(fg_com);
    gtk_table_attach(GTK_TABLE(table1), fg_com, 2, 3, 0, 1,
		     (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		     (GtkAttachOptions) (0), 0, 0);
    fg_com_items = g_list_append(fg_com_items, _("sine"));
    fg_com_items = g_list_append(fg_com_items, _("tangent"));
    fg_com_items = g_list_append(fg_com_items, _("arc sine"));
    fg_com_items = g_list_append(fg_com_items, _("random"));
    gtk_combo_set_popdown_strings(GTK_COMBO(fg_com), fg_com_items);
    g_list_free(fg_com_items);

    fg_com_ent = GTK_COMBO(fg_com)->entry;
    gtk_widget_ref(fg_com_ent);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "fg_com_ent", fg_com_ent,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(fg_com_ent);
    gtk_widget_set_usize(fg_com_ent, 100, -2);
    gtk_entry_set_editable(GTK_ENTRY(fg_com_ent), FALSE);
    gtk_entry_set_text(GTK_ENTRY(fg_com_ent), _("sine"));

    fg_com2 = gtk_combo_new();
    gtk_widget_ref(fg_com2);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "fg_com2", fg_com2,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(fg_com2);
    gtk_table_attach(GTK_TABLE(table1), fg_com2, 2, 3, 1, 2,
		     (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		     (GtkAttachOptions) (0), 0, 0);
    fg_com2_items = g_list_append(fg_com2_items, _("inc"));
    fg_com2_items = g_list_append(fg_com2_items, _("scan"));
    fg_com2_items = g_list_append(fg_com2_items, _("random"));
    gtk_combo_set_popdown_strings(GTK_COMBO(fg_com2), fg_com2_items);
    g_list_free(fg_com2_items);

    fg_com2_ent = GTK_COMBO(fg_com2)->entry;
    gtk_widget_ref(fg_com2_ent);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "fg_com2_ent", fg_com2_ent,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(fg_com2_ent);
    gtk_widget_set_usize(fg_com2_ent, 100, -2);
    gtk_entry_set_editable(GTK_ENTRY(fg_com2_ent), FALSE);
    gtk_entry_set_text(GTK_ENTRY(fg_com2_ent), _("inc"));

    fg_a_ent = gtk_entry_new();
    gtk_widget_ref(fg_a_ent);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "fg_a_ent", fg_a_ent,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(fg_a_ent);
    gtk_table_attach(GTK_TABLE(table1), fg_a_ent, 1, 2, 0, 1,
		     (GtkAttachOptions) (0), (GtkAttachOptions) (0), 0, 0);
    gtk_widget_set_usize(fg_a_ent, 32, -2);

    fg_d_ent = gtk_entry_new();
    gtk_widget_ref(fg_d_ent);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "fg_d_ent", fg_d_ent,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(fg_d_ent);
    gtk_table_attach(GTK_TABLE(table1), fg_d_ent, 1, 2, 1, 2,
		     (GtkAttachOptions) (0), (GtkAttachOptions) (0), 0, 0);
    gtk_widget_set_usize(fg_d_ent, 32, -2);

    man_frame = gtk_frame_new(NULL);
    gtk_widget_ref(man_frame);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "man_frame", man_frame,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(man_frame);
    gtk_box_pack_start(GTK_BOX(hbox2), man_frame, TRUE, TRUE, 0);

    vbox5 = gtk_vbox_new(FALSE, 0);
    gtk_widget_ref(vbox5);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "vbox5", vbox5,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(vbox5);
    gtk_container_add(GTK_CONTAINER(man_frame), vbox5);

    man_lab = gtk_label_new(_("Manual Command"));
    gtk_widget_ref(man_lab);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "man_lab", man_lab,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(man_lab);
    gtk_box_pack_start(GTK_BOX(vbox5), man_lab, FALSE, FALSE, 0);
    gtk_label_set_justify(GTK_LABEL(man_lab), GTK_JUSTIFY_LEFT);

    hbox5 = gtk_hbox_new(FALSE, 0);
    gtk_widget_ref(hbox5);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "hbox5", hbox5,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(hbox5);
    gtk_box_pack_start(GTK_BOX(vbox5), hbox5, TRUE, TRUE, 0);

    man_ent = gtk_entry_new();
    gtk_widget_ref(man_ent);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "man_ent", man_ent,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(man_ent);
    gtk_box_pack_start(GTK_BOX(hbox5), man_ent, TRUE, TRUE, 0);
    gtk_widget_set_usize(man_ent, 100, -2);
    gtk_tooltips_set_tip(tooltips, man_ent, _("Send command"), NULL);

    man_btn = gtk_button_new_with_label(_("SEND"));
    gtk_widget_ref(man_btn);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "man_btn", man_btn,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(man_btn);
    gtk_box_pack_start(GTK_BOX(hbox5), man_btn, FALSE, FALSE, 0);
    gtk_widget_add_accelerator(man_btn, "released", accel_group,
			       GDK_Return, 0, GTK_ACCEL_VISIBLE);

    hbox8 = gtk_hbox_new(FALSE, 0);
    gtk_widget_ref(hbox8);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "hbox8", hbox8,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(hbox8);
    gtk_box_pack_start(GTK_BOX(vbox5), hbox8, FALSE, FALSE, 0);

    man_ent2 = gtk_entry_new();
    gtk_widget_ref(man_ent2);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "man_ent2", man_ent2,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(man_ent2);
    gtk_box_pack_start(GTK_BOX(hbox8), man_ent2, TRUE, TRUE, 0);
    gtk_widget_set_usize(man_ent2, 100, -2);
    gtk_widget_set_sensitive(man_ent2, FALSE);
    GTK_WIDGET_UNSET_FLAGS(man_ent2, GTK_CAN_FOCUS);
    gtk_tooltips_set_tip(tooltips, man_ent2, _("Response"), NULL);
    gtk_entry_set_editable(GTK_ENTRY(man_ent2), FALSE);

    man_ent3 = gtk_entry_new();
    gtk_widget_ref(man_ent3);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "man_ent3", man_ent3,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(man_ent3);
    gtk_box_pack_start(GTK_BOX(hbox8), man_ent3, FALSE, FALSE, 0);
    gtk_widget_set_usize(man_ent3, 40, -2);
    gtk_widget_set_sensitive(man_ent3, FALSE);
    GTK_WIDGET_UNSET_FLAGS(man_ent3, GTK_CAN_FOCUS);
    gtk_tooltips_set_tip(tooltips, man_ent3, _("Attempted counter"), NULL);
    gtk_entry_set_editable(GTK_ENTRY(man_ent3), FALSE);

    frame2 = gtk_frame_new(NULL);
    gtk_widget_ref(frame2);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "frame2", frame2,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(frame2);
    gtk_box_pack_start(GTK_BOX(vbox1), frame2, TRUE, TRUE, 0);

    hbox9 = gtk_hbox_new(FALSE, 0);
    gtk_widget_ref(hbox9);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "hbox9", hbox9,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(hbox9);
    gtk_container_add(GTK_CONTAINER(frame2), hbox9);

    hs_ent = gtk_entry_new();
    gtk_widget_ref(hs_ent);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "hs_ent", hs_ent,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(hs_ent);
    gtk_box_pack_start(GTK_BOX(hbox9), hs_ent, FALSE, FALSE, 0);
    gtk_widget_set_usize(hs_ent, 32, -2);

    hscale1 =
	gtk_hscale_new(GTK_ADJUSTMENT
		       (gtk_adjustment_new(0, 0, 10, 0.001, 1, 0)));
    gtk_widget_ref(hscale1);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "hscale1", hscale1,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(hscale1);
    gtk_box_pack_start(GTK_BOX(hbox9), hscale1, TRUE, TRUE, 0);
    gtk_scale_set_digits(GTK_SCALE(hscale1), 3);

    draw_frame = gtk_frame_new(NULL);
    gtk_widget_ref(draw_frame);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "draw_frame", draw_frame,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(draw_frame);
    gtk_box_pack_start(GTK_BOX(vbox1), draw_frame, TRUE, TRUE, 0);

    vbox6 = gtk_vbox_new(FALSE, 0);
    gtk_widget_ref(vbox6);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "vbox6", vbox6,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(vbox6);
    gtk_container_add(GTK_CONTAINER(draw_frame), vbox6);

    draw_lab = gtk_label_new(_("DAQ Analog In"));
    gtk_widget_ref(draw_lab);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "draw_lab", draw_lab,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(draw_lab);
    gtk_box_pack_start(GTK_BOX(vbox6), draw_lab, FALSE, FALSE, 0);
    gtk_label_set_justify(GTK_LABEL(draw_lab), GTK_JUSTIFY_LEFT);

    hbox6 = gtk_hbox_new(FALSE, 0);
    gtk_widget_ref(hbox6);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "hbox6", hbox6,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(hbox6);
    gtk_box_pack_start(GTK_BOX(vbox6), hbox6, TRUE, TRUE, 0);

    draw_ent = gtk_entry_new();
    gtk_widget_ref(draw_ent);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "draw_ent", draw_ent,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(draw_ent);
    gtk_box_pack_start(GTK_BOX(hbox6), draw_ent, FALSE, FALSE, 0);
    gtk_widget_set_usize(draw_ent, 32, -2);

    hbox11 = gtk_hbox_new(FALSE, 0);
    gtk_widget_ref(hbox11);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "hbox11", hbox11,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(hbox11);
    gtk_box_pack_start(GTK_BOX(hbox6), hbox11, TRUE, FALSE, 0);

    draw_ent2 = gtk_entry_new();
    gtk_widget_ref(draw_ent2);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "draw_ent2", draw_ent2,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(draw_ent2);
    gtk_box_pack_start(GTK_BOX(hbox6), draw_ent2, FALSE, FALSE, 0);
    gtk_widget_set_usize(draw_ent2, 64, -2);
    GTK_WIDGET_UNSET_FLAGS(draw_ent2, GTK_CAN_FOCUS);
    gtk_entry_set_editable(GTK_ENTRY(draw_ent2), FALSE);

    draw_ent3 = gtk_entry_new();
    gtk_widget_ref(draw_ent3);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "draw_ent3", draw_ent3,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(draw_ent3);
    gtk_box_pack_start(GTK_BOX(hbox6), draw_ent3, FALSE, FALSE, 0);
    gtk_widget_set_usize(draw_ent3, 24, -2);
    GTK_WIDGET_UNSET_FLAGS(draw_ent3, GTK_CAN_FOCUS);
    gtk_entry_set_editable(GTK_ENTRY(draw_ent3), FALSE);

    hbox12 = gtk_hbox_new(FALSE, 0);
    gtk_widget_ref(hbox12);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "hbox12", hbox12,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(hbox12);
    gtk_box_pack_start(GTK_BOX(hbox6), hbox12, FALSE, FALSE, 0);
    gtk_widget_set_usize(hbox12, 32, -2);

    draw_tbtn = gtk_toggle_button_new_with_label(_("READ"));
    gtk_widget_ref(draw_tbtn);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "draw_tbtn", draw_tbtn,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(draw_tbtn);
    gtk_box_pack_start(GTK_BOX(hbox6), draw_tbtn, FALSE, FALSE, 0);

    draw = gtk_drawing_area_new();
    gtk_widget_ref(draw);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "draw", draw,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(draw);
    gtk_box_pack_start(GTK_BOX(vbox6), draw, TRUE, TRUE, 0);
    gtk_widget_set_usize(draw, 400, 100);
    gtk_widget_set_events(draw,
			  GDK_EXPOSURE_MASK | GDK_POINTER_MOTION_MASK |
			  GDK_POINTER_MOTION_HINT_MASK |
			  GDK_BUTTON_PRESS_MASK | GDK_LEAVE_NOTIFY_MASK);

    frame8 = gtk_frame_new(NULL);
    gtk_widget_ref(frame8);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "frame8", frame8,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(frame8);
    gtk_box_pack_start(GTK_BOX(vbox1), frame8, TRUE, TRUE, 0);

    table2 = gtk_table_new(2, 8, FALSE);
    gtk_widget_ref(table2);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "table2", table2,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(table2);
    gtk_container_add(GTK_CONTAINER(frame8), table2);

    label5 = gtk_label_new(_("D/I "));
    gtk_widget_ref(label5);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "label5", label5,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(label5);
    gtk_table_attach(GTK_TABLE(table2), label5, 0, 1, 0, 1,
		     (GtkAttachOptions) (0), (GtkAttachOptions) (0), 0, 0);

    label6 = gtk_label_new(_("D/O "));
    gtk_widget_ref(label6);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "label6", label6,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(label6);
    gtk_table_attach(GTK_TABLE(table2), label6, 0, 1, 1, 2,
		     (GtkAttachOptions) (0), (GtkAttachOptions) (0), 0, 0);

    frame12 = gtk_frame_new(NULL);
    gtk_widget_ref(frame12);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "frame12", frame12,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(frame12);
    gtk_table_attach(GTK_TABLE(table2), frame12, 5, 6, 0, 1,
		     (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		     (GtkAttachOptions) (GTK_FILL), 0, 0);

    di4 = create_pixmap(iwc, "lemp0_12.xpm", FALSE);
    gtk_widget_ref(di4);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "di4", di4,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(di4);
    gtk_container_add(GTK_CONTAINER(frame12), di4);

    frame11 = gtk_frame_new(NULL);
    gtk_widget_ref(frame11);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "frame11", frame11,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(frame11);
    gtk_table_attach(GTK_TABLE(table2), frame11, 4, 5, 0, 1,
		     (GtkAttachOptions) (GTK_FILL),
		     (GtkAttachOptions) (GTK_FILL), 0, 0);

    di3 = create_pixmap(iwc, "lemp0_12.xpm", FALSE);
    gtk_widget_ref(di3);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "di3", di3,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(di3);
    gtk_container_add(GTK_CONTAINER(frame11), di3);

    frame10 = gtk_frame_new(NULL);
    gtk_widget_ref(frame10);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "frame10", frame10,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(frame10);
    gtk_table_attach(GTK_TABLE(table2), frame10, 3, 4, 0, 1,
		     (GtkAttachOptions) (GTK_FILL),
		     (GtkAttachOptions) (GTK_FILL), 0, 0);

    di2 = create_pixmap(iwc, "lemp0_12.xpm", FALSE);
    gtk_widget_ref(di2);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "di2", di2,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(di2);
    gtk_container_add(GTK_CONTAINER(frame10), di2);

    frame9 = gtk_frame_new(NULL);
    gtk_widget_ref(frame9);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "frame9", frame9,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(frame9);
    gtk_table_attach(GTK_TABLE(table2), frame9, 2, 3, 0, 1,
		     (GtkAttachOptions) (GTK_FILL),
		     (GtkAttachOptions) (GTK_FILL), 0, 0);

    di1 = create_pixmap(iwc, "lemp0_12.xpm", FALSE);
    gtk_widget_ref(di1);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "di1", di1,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(di1);
    gtk_container_add(GTK_CONTAINER(frame9), di1);

    do_ent = gtk_entry_new();
    gtk_widget_ref(do_ent);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "do_ent", do_ent,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(do_ent);
    gtk_table_attach(GTK_TABLE(table2), do_ent, 1, 2, 1, 2,
		     (GtkAttachOptions) (0), (GtkAttachOptions) (0), 0, 0);
    gtk_widget_set_usize(do_ent, 36, -2);

    di_ent = gtk_entry_new();
    gtk_widget_ref(di_ent);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "di_ent", di_ent,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(di_ent);
    gtk_table_attach(GTK_TABLE(table2), di_ent, 1, 2, 0, 1,
		     (GtkAttachOptions) (0), (GtkAttachOptions) (0), 0, 0);
    gtk_widget_set_usize(di_ent, 36, -2);

    do4 = gtk_toggle_button_new_with_label(_("DO 4"));
    gtk_widget_ref(do4);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "do4", do4,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(do4);
    gtk_table_attach(GTK_TABLE(table2), do4, 5, 6, 1, 2,
		     (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		     (GtkAttachOptions) (GTK_EXPAND), 0, 0);

    do3 = gtk_toggle_button_new_with_label(_("DO 3"));
    gtk_widget_ref(do3);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "do3", do3,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(do3);
    gtk_table_attach(GTK_TABLE(table2), do3, 4, 5, 1, 2,
		     (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		     (GtkAttachOptions) (GTK_EXPAND), 0, 0);

    do2 = gtk_toggle_button_new_with_label(_("DO 2"));
    gtk_widget_ref(do2);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "do2", do2,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(do2);
    gtk_table_attach(GTK_TABLE(table2), do2, 3, 4, 1, 2,
		     (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		     (GtkAttachOptions) (GTK_EXPAND), 0, 0);

    do1 = gtk_toggle_button_new_with_label(_("DO 1"));
    gtk_widget_ref(do1);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "do1", do1,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(do1);
    gtk_table_attach(GTK_TABLE(table2), do1, 2, 3, 1, 2,
		     (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		     (GtkAttachOptions) (GTK_EXPAND), 0, 0);

    di_tbtn = gtk_toggle_button_new_with_label(_("READ"));
    gtk_widget_ref(di_tbtn);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "di_tbtn", di_tbtn,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(di_tbtn);
    gtk_table_attach(GTK_TABLE(table2), di_tbtn, 7, 8, 0, 1,
		     (GtkAttachOptions) (0), (GtkAttachOptions) (0), 0, 0);

    lemp_inv = gtk_toggle_button_new_with_label(_("INV"));
    gtk_widget_ref(lemp_inv);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "lemp_inv", lemp_inv,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(lemp_inv);
    gtk_table_attach(GTK_TABLE(table2), lemp_inv, 6, 7, 0, 1,
		     (GtkAttachOptions) (0), (GtkAttachOptions) (0), 0, 0);

    do_tbtn = gtk_toggle_button_new_with_label(_("Align"));
    gtk_widget_ref(do_tbtn);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "do_tbtn", do_tbtn,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(do_tbtn);
    gtk_table_attach(GTK_TABLE(table2), do_tbtn, 6, 8, 1, 2,
		     (GtkAttachOptions) (GTK_FILL),
		     (GtkAttachOptions) (0), 0, 0);

    frame13 = gtk_frame_new(NULL);
    gtk_widget_ref(frame13);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "frame13", frame13,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(frame13);
    gtk_box_pack_start(GTK_BOX(vbox1), frame13, TRUE, TRUE, 0);

    hbox10 = gtk_hbox_new(FALSE, 0);
    gtk_widget_ref(hbox10);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "hbox10", hbox10,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(hbox10);
    gtk_container_add(GTK_CONTAINER(frame13), hbox10);

    frame14 = gtk_frame_new(NULL);
    gtk_widget_ref(frame14);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "frame14", frame14,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(frame14);
    gtk_box_pack_start(GTK_BOX(hbox10), frame14, FALSE, FALSE, 0);
    gtk_widget_set_usize(frame14, 32, -2);

    beat_lemp = create_pixmap(iwc, "lemp0_12.xpm", FALSE);
    gtk_widget_ref(beat_lemp);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "beat_lemp", beat_lemp,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(beat_lemp);
    gtk_container_add(GTK_CONTAINER(frame14), beat_lemp);

    label7 = gtk_label_new(_("Time Beat Interval "));
    gtk_widget_ref(label7);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "label7", label7,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(label7);
    gtk_box_pack_start(GTK_BOX(hbox10), label7, FALSE, FALSE, 0);

    beat_sb_adj = gtk_adjustment_new(50, 0, 1000, 1, 10, 10);
    beat_sb = gtk_spin_button_new(GTK_ADJUSTMENT(beat_sb_adj), 1, 0);
    gtk_widget_ref(beat_sb);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "beat_sb", beat_sb,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(beat_sb);
    gtk_box_pack_start(GTK_BOX(hbox10), beat_sb, FALSE, FALSE, 0);

    label8 = gtk_label_new(_(" x 10ms = "));
    gtk_widget_ref(label8);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "label8", label8,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(label8);
    gtk_box_pack_start(GTK_BOX(hbox10), label8, FALSE, FALSE, 0);

    beat_ent = gtk_entry_new();
    gtk_widget_ref(beat_ent);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "beat_ent", beat_ent,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(beat_ent);
    gtk_box_pack_start(GTK_BOX(hbox10), beat_ent, FALSE, FALSE, 0);
    gtk_widget_set_usize(beat_ent, 50, -2);
    GTK_WIDGET_UNSET_FLAGS(beat_ent, GTK_CAN_FOCUS);
    gtk_entry_set_editable(GTK_ENTRY(beat_ent), FALSE);

    label9 = gtk_label_new(_("ms        "));
    gtk_widget_ref(label9);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "label9", label9,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(label9);
    gtk_box_pack_start(GTK_BOX(hbox10), label9, TRUE, TRUE, 0);

    beat_tbtn = gtk_toggle_button_new_with_label(_("  Beat  "));
    gtk_widget_ref(beat_tbtn);
    gtk_object_set_data_full(GTK_OBJECT(iwc), "beat_tbtn", beat_tbtn,
			     (GtkDestroyNotify) gtk_widget_unref);
    gtk_widget_show(beat_tbtn);
    gtk_box_pack_start(GTK_BOX(hbox10), beat_tbtn, FALSE, FALSE, 0);

    gtk_signal_connect(GTK_OBJECT(iwc), "delete_event",
		       GTK_SIGNAL_FUNC(quit), NULL);
    gtk_signal_connect(GTK_OBJECT(iwc), "realize",
		       GTK_SIGNAL_FUNC(on_NAP1_realize), draw);
    gtk_signal_connect(GTK_OBJECT(cnt_lemp), "realize",
		       GTK_SIGNAL_FUNC(on_cnt_lemp_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(ip_ent), "realize",
		       GTK_SIGNAL_FUNC(on_ip_ent_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(port_ent), "realize",
		       GTK_SIGNAL_FUNC(on_port_ent_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(cnt_btn), "toggled",
		       GTK_SIGNAL_FUNC(on_cnt_btn_toggled), NULL);
    gtk_signal_connect(GTK_OBJECT(fg_tbtn), "toggled",
		       GTK_SIGNAL_FUNC(on_fg_tbtn_toggled), NULL);
    gtk_signal_connect(GTK_OBJECT(fg_tbtn), "realize",
		       GTK_SIGNAL_FUNC(on_fg_tbtn_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(fg_tbtn2), "toggled",
		       GTK_SIGNAL_FUNC(on_fg_tbtn2_toggled), NULL);
    gtk_signal_connect(GTK_OBJECT(fg_tbtn2), "realize",
		       GTK_SIGNAL_FUNC(on_fg_tbtn2_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(fg_com), "realize",
		       GTK_SIGNAL_FUNC(on_fg_com_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(fg_com_ent), "changed",
		       GTK_SIGNAL_FUNC(on_fg_com_ent_changed), NULL);
    gtk_signal_connect(GTK_OBJECT(fg_com2), "realize",
		       GTK_SIGNAL_FUNC(on_fg_com2_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(fg_com2_ent), "changed",
		       GTK_SIGNAL_FUNC(on_fg_com2_ent_changed), NULL);
    gtk_signal_connect(GTK_OBJECT(fg_a_ent), "realize",
		       GTK_SIGNAL_FUNC(on_fg_a_ent_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(fg_a_ent), "changed",
		       GTK_SIGNAL_FUNC(on_fg_a_ent_changed), NULL);
    gtk_signal_connect(GTK_OBJECT(fg_d_ent), "realize",
		       GTK_SIGNAL_FUNC(on_fg_d_ent_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(fg_d_ent), "changed",
		       GTK_SIGNAL_FUNC(on_fg_d_ent_changed), NULL);
    gtk_signal_connect(GTK_OBJECT(man_ent), "realize",
		       GTK_SIGNAL_FUNC(on_man_ent_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(man_ent), "key_press_event",
		       GTK_SIGNAL_FUNC(on_man_ent_key_press_event), NULL);
    gtk_signal_connect(GTK_OBJECT(man_btn), "released",
		       GTK_SIGNAL_FUNC(on_man_btn_released), man_ent);
    gtk_signal_connect(GTK_OBJECT(man_btn), "realize",
		       GTK_SIGNAL_FUNC(on_man_btn_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(man_ent2), "realize",
		       GTK_SIGNAL_FUNC(on_man_ent2_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(man_ent3), "realize",
		       GTK_SIGNAL_FUNC(on_man_ent3_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(hs_ent), "realize",
		       GTK_SIGNAL_FUNC(on_hs_ent_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(hs_ent), "changed",
		       GTK_SIGNAL_FUNC(on_hs_ent_changed), NULL);
    gtk_signal_connect(GTK_OBJECT(hscale1), "button_release_event",
		       GTK_SIGNAL_FUNC(on_hscale1_button_release_event),
		       NULL);
    gtk_signal_connect(GTK_OBJECT(hscale1), "key_press_event",
		       GTK_SIGNAL_FUNC(on_hscale1_key_press_event), NULL);
    gtk_signal_connect(GTK_OBJECT(hscale1), "realize",
		       GTK_SIGNAL_FUNC(on_hscale1_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(draw_ent), "realize",
		       GTK_SIGNAL_FUNC(on_draw_ent_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(draw_ent), "changed",
		       GTK_SIGNAL_FUNC(on_draw_ent_changed), NULL);
    gtk_signal_connect(GTK_OBJECT(draw_ent2), "realize",
		       GTK_SIGNAL_FUNC(on_draw_ent2_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(draw_ent3), "realize",
		       GTK_SIGNAL_FUNC(on_draw_ent3_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(draw_tbtn), "toggled",
		       GTK_SIGNAL_FUNC(on_draw_tbtn_toggled), NULL);
    gtk_signal_connect(GTK_OBJECT(draw_tbtn), "realize",
		       GTK_SIGNAL_FUNC(on_draw_tbtn_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(draw), "configure_event",
		       GTK_SIGNAL_FUNC(on_draw_configure_event), NULL);
    gtk_signal_connect(GTK_OBJECT(draw), "expose_event",
		       GTK_SIGNAL_FUNC(on_draw_expose_event), NULL);
    gtk_signal_connect(GTK_OBJECT(draw), "button_press_event",
		       GTK_SIGNAL_FUNC(on_draw_button_press_event), NULL);
    gtk_signal_connect(GTK_OBJECT(draw), "motion_notify_event",
		       GTK_SIGNAL_FUNC(on_draw_motion_notify_event), NULL);
    gtk_signal_connect(GTK_OBJECT(draw), "realize",
		       GTK_SIGNAL_FUNC(on_draw_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(di4), "realize",
		       GTK_SIGNAL_FUNC(on_di4_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(di3), "realize",
		       GTK_SIGNAL_FUNC(on_di3_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(di2), "realize",
		       GTK_SIGNAL_FUNC(on_di2_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(di1), "realize",
		       GTK_SIGNAL_FUNC(on_di1_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(do_ent), "realize",
		       GTK_SIGNAL_FUNC(on_do_ent_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(do_ent), "changed",
		       GTK_SIGNAL_FUNC(on_do_ent_changed), NULL);
    gtk_signal_connect(GTK_OBJECT(di_ent), "realize",
		       GTK_SIGNAL_FUNC(on_di_ent_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(di_ent), "changed",
		       GTK_SIGNAL_FUNC(on_di_ent_changed), NULL);
    gtk_signal_connect(GTK_OBJECT(do4), "toggled",
		       GTK_SIGNAL_FUNC(on_do4_toggled), NULL);
    gtk_signal_connect(GTK_OBJECT(do4), "realize",
		       GTK_SIGNAL_FUNC(on_do4_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(do3), "toggled",
		       GTK_SIGNAL_FUNC(on_do3_toggled), NULL);
    gtk_signal_connect(GTK_OBJECT(do3), "realize",
		       GTK_SIGNAL_FUNC(on_do3_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(do2), "toggled",
		       GTK_SIGNAL_FUNC(on_do2_toggled), NULL);
    gtk_signal_connect(GTK_OBJECT(do2), "realize",
		       GTK_SIGNAL_FUNC(on_do2_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(do1), "toggled",
		       GTK_SIGNAL_FUNC(on_do1_toggled), NULL);
    gtk_signal_connect(GTK_OBJECT(do1), "realize",
		       GTK_SIGNAL_FUNC(on_do1_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(di_tbtn), "toggled",
		       GTK_SIGNAL_FUNC(on_di_tbtn_toggled), NULL);
    gtk_signal_connect(GTK_OBJECT(di_tbtn), "realize",
		       GTK_SIGNAL_FUNC(on_di_tbtn_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(lemp_inv), "realize",
		       GTK_SIGNAL_FUNC(on_lemp_inv_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(lemp_inv), "toggled",
		       GTK_SIGNAL_FUNC(on_lemp_inv_toggled), NULL);
    gtk_signal_connect(GTK_OBJECT(do_tbtn), "toggled",
		       GTK_SIGNAL_FUNC(on_do_tbtn_toggled), NULL);
    gtk_signal_connect(GTK_OBJECT(do_tbtn), "realize",
		       GTK_SIGNAL_FUNC(on_do_tbtn_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(beat_lemp), "realize",
		       GTK_SIGNAL_FUNC(on_beat_lemp_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(beat_sb), "realize",
		       GTK_SIGNAL_FUNC(on_beat_sb_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(beat_sb), "changed",
		       GTK_SIGNAL_FUNC(on_beat_sb_changed), NULL);
    gtk_signal_connect(GTK_OBJECT(beat_ent), "realize",
		       GTK_SIGNAL_FUNC(on_beat_ent_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(beat_tbtn), "realize",
		       GTK_SIGNAL_FUNC(on_beat_tbtn_realize), NULL);
    gtk_signal_connect(GTK_OBJECT(beat_tbtn), "toggled",
		       GTK_SIGNAL_FUNC(on_beat_tbtn_toggled), NULL);

    gtk_object_set_data(GTK_OBJECT(iwc), "tooltips", tooltips);

    gtk_window_add_accel_group(GTK_WINDOW(iwc), accel_group);

    return iwc;
}
